### ISSUE TITLE
I am getting this error, I have opencv3 and Python 2.7 running on windows 

### ISSUE THREAD

**Issue by arsalan993** [developer-aj/TextDetection#2]
Traceback (most recent call last):
  File ".\swt_new.py", line 232, in <module>
    swt("036.jpg", -1)
  File ".\swt_new.py", line 139, in swt
    if edgeMap[nextX][nextY]:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by liyandongpy** [comment]
me too
